#todo delete this file
name: nycbuswatcher
channels:
  - conda-forge
  - defaults
dependencies:
  - aniso8601=8.0.0
  - apscheduler=3.6.3
  - async_generator=1.10
  - attrs=20.2.0
  - boost-cpp=1.72.0
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - contextvars=2.4
  - cryptography=3.1.1
  - curl=7.71.1
  - dash=1.20.0
  - dash-core-components=1.16.0
  - dash-html-components=1.1.3
  - dash-renderer=1.9.1
  - dash-table=4.11.3
  - dnspython=2.0.0
  - expat=2.2.9
  - fiona=1.8.17
  - flask=1.1.2
  - flask-compress=1.9.0
  - flask-cors=3.0.8
  - flask-restful=0.3.8
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - future=0.18.2
  - gdal=3.1.4
  - geojson=2.5.0
  - geopandas=0.9.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.2
  - gunicorn=20.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=67.1
  - idna=2.10
  - immutables=0.14
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.13
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libcxx=10.0.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgdal=3.1.4
  # - libgfortran=5.0.0
  # - libgfortran5=9.3.0
  - libglib=2.66.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.13.0.1
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.1
  - lz4-c=1.9.2
  - mako=1.1.4
  - markupsafe=1.1.1
  - marshmallow=3.8.0
  - munch=2.5.0
  - mysql-common=8.0.21
  - mysql-connector-python=8.0.21
  - mysql-libs=8.0.21
  - ncurses=6.2
  - numpy=1.19.2
  - openjpeg=2.3.1
  - openssl=1.1.1k
  - outcome=1.0.1
  - pandas=1.1.3
  - pcre=8.44
  - pip=20.2.3
  - pixman=0.40.0
  - plotly=4.14.3
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.1.1
  - protobuf=3.13.0.1
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python=3.6.11
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python-editor=1.0.4
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.4.1
  - readline=8.0
  - requests=2.24.0
  - retrying=1.3.3
  - rtree=0.9.7
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sniffio=1.2.0
  - sortedcontainers=2.2.2
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - tiledb=2.1.2
  - tk=8.6.10
  - trio=0.17.0
  - tzcode=2021a
  - tzlocal=2.1
  - urllib3=1.25.10
  - werkzeug=1.0.1
  - wheel=0.35.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - anyio==1.4.0
    - asks==2.4.10
    - dash-bootstrap-components==0.12.0
    - dataclasses==0.7
    - h11==0.11.0
    - mysqlclient==2.0.1
    - typing-extensions==3.7.4.3
prefix: /opt/bin/miniconda3/envs/nycbuswatcher
